### ISSUE TITLE
"Last Placed" BG Image Causing Issues

### ISSUE THREAD

**Issue by TylerSmall19** [TylerSmall19/teamdave#11]
So, basically on lines 93 - 95 in the script.js 

```
    // Get layer we just added and select it

    var length = $comicCanvas.getLayers().length;

    var layer = $comicCanvas.getLayers()[length - 1];

    selectLayer(layer);
```

We are having issues with unwanted selection when the BG image is switched, since the BG images always go to index 0. It's being caused by the BG going down, then these lines running and selecting the last index in the layers array (which isn't the BG image put down, it's an image put down less recently)

**Comment by TylerSmall19** [comment]
Issue resolved thru refactoring of logic. Pull Request #13

**Comment by olishmollie** [comment]
Ah I see, so when you switch the background a layer was being selected. Nice fix!
